version: 0.0
os: linux
files:
  - source: ./webgoat-server-v8.1.0.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: install_java.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
