version: 0.0
os: linux
files:
  - source: webgoat-server-v8.1.0.jar
    destination: /tmp
  - source: Dependency-Check-Scan.xml
    destination: /tmp
  - source: Snyk-Scan.json
    destination: /tmp
  - source: class-report.xml
    destination: /tmp
  - source: dd_upload.py
    destination: /tmp
  - source: dd_config.py
    destination: /tmp

hooks:

  BeforeInstall:
    - location: cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: install_java.sh
      timeout: 300
      runas: root
    - location: start_server.sh
      timeout: 300
      runas: root
    - location: run_dast.sh
      timeout: 300
      runas: root
    - location: upload_report.sh
      timeout: 300
      runas: root
