version: 0.0
os: linux
    
hooks:
  AfterInstall:
    - location: scripts/install_java.sh
      timeout: 300
      runas: root
    # - location: scripts/start_server.sh
    #   timeout: 300
    #   runas: root
    - location: scripts/run_dast.sh
      timeout: 300
      runas: root
    # - location: scripts/upload_report.sh
    #   timeout: 300
    #   runas: root
