version: 0.0
os: linux
files:
  - overwrite: true 
  - source: /
    destination: /tmp
  # - source: ./webgoat-server-v8.1.0.jar
  #   destination: /tmp
  # - source: ./Dependency-Check-Scan.xml
  #   destination: /tmp
  # - source: ./Snyk-Scan.json
  #   destination: /tmp
  # - source: ./class-report.xml
  #   destination: /tmp
    
hooks:
  AfterInstall:
    - location: install_java.sh
      timeout: 300
      runas: root
    # - location: start_server.sh
    #   timeout: 300
    #   runas: root
    - location: run_dast.sh
      timeout: 300
      runas: root
    - location: upload_report.sh
      timeout: 300
      runas: root
