version: 0.0
os: linux
files:
  - source: ./webgoat-server-v8.1.0.jar
    destination: /tmp
    
hooks:
  AfterInstall:
    - location: install_java.sh
      timeout: 300
      runas: root
    # - location: start_server.sh
    #   timeout: 300
    #   runas: root
    - location: run_dast.sh
      timeout: 300
      runas: root
