version: 0.1

phases:
  build:
    commands:
      - mvn package -DskipTests

artifacts:
  files:
    - webgoat-server/target/webgoat-server-v8.1.0.jar
    - appspec.yml
    - scripts/start_server.sh
  discard-paths: yes

